# Generated by Django 6.0.5 on 2026-05-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("BUYER", "Buyer"),
                    ("SELLER", "Seller"),
                    ("TRANSPORTER", "Transporter"),
                ],
                max_length=20,
            ),
        ),
    ]
