# Generated by Django 6.0.5 on 2026-05-11 19:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="full",
            new_name="full_name",
        ),
    ]
