# Generated by Django 6.0.5 on 2026-05-12 21:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rename_full_user_full_name"),
        ("orders", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("bank_code", models.CharField(max_length=10)),
                ("account_number", models.CharField(max_length=20)),
                ("account_name", models.CharField(max_length=255)),
                ("remark", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("squad_response", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VirtualAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("0daf9781-1a03-4ac9-8f55-257879e6c93b"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "virtual_account_number",
                    models.CharField(max_length=20, unique=True),
                ),
                ("bank_name", models.CharField(max_length=100)),
                ("account_name", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("mobile_num", models.CharField(max_length=14)),
                ("bvn", models.CharField(max_length=11)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VirtualAccountTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("e8a55a25-c53b-4e5b-b4dc-643ac6028ca0"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "pricipal_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "settled_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("fee", models.DecimalField(decimal_places=2, max_digits=12)),
                ("sender", models.CharField(max_length=255)),
                ("remarks", models.TextField()),
                ("currency", models.CharField(default="NGN", max_length=3)),
                ("transaction_date", models.DateTimeField()),
                ("webhook_processed", models.BooleanField(default=False)),
                ("webhook_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="accounts.buyerprofile",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="channel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USSD", "ussd"),
                    ("CARD", "card"),
                    ("TRANSFER", "Transfer"),
                    ("VIRTUAL-ACCOUNT", "virtual-account"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="checkout_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                choices=[("USD", "usd"), ("NGN", "ngn")], default="NGN", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="gateway_response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="payment",
            name="webhook_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="payment",
            name="webhook_recieved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="webhook_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["squad_transaction_id"], name="payments_pa_squad_t_43f8c3_idx"
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers",
                to="accounts.farmerprofile",
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="transporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers",
                to="accounts.transporterprofile",
            ),
        ),
        migrations.AddField(
            model_name="virtualaccount",
            name="farmer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="virtual_account",
                to="accounts.farmerprofile",
            ),
        ),
        migrations.AddField(
            model_name="virtualaccount",
            name="transporter",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="virtual_account",
                to="accounts.transporterprofile",
            ),
        ),
        migrations.AddField(
            model_name="virtualaccounttransaction",
            name="virtual_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="payments.virtualaccount",
            ),
        ),
        migrations.AddIndex(
            model_name="virtualaccounttransaction",
            index=models.Index(
                fields=["transaction_reference"], name="payments_vi_transac_c30fed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="virtualaccounttransaction",
            index=models.Index(
                fields=["virtual_account", "-transaction_date"],
                name="payments_vi_virtual_dfcafb_idx",
            ),
        ),
    ]
