# Generated by Django 6.0.5 on 2026-05-11 21:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0003_rename_full_user_full_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produce",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("produce_name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("VEGETABLES", "Vegetables"),
                            ("FRUITS", "Fruits"),
                            ("GRAINS", "Grains"),
                            ("DAIRY", "Dairy"),
                            ("MEAT", "Meat"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity_available", models.IntegerField()),
                ("harvest_date", models.DateField()),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("LOW_STOCK", "Low Stock"),
                            ("SOLD_OUT", "Sold Out"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produces",
                        to="accounts.farmerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["farmer", "-created_at"],
                        name="produce_pro_farmer__c77411_idx",
                    ),
                    models.Index(
                        fields=["availability_status"],
                        name="produce_pro_availab_bf630f_idx",
                    ),
                    models.Index(
                        fields=["category"], name="produce_pro_categor_eac7ea_idx"
                    ),
                ],
            },
        ),
    ]
